Traceback (most recent call last):
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\scripts\popsimToDaysimMerge.py", line 23, in <module>
    gq = pd.read_csv(os.path.join(outputDir, 'household_2017_GQ.dat'), sep = ' ')
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\Setup\software\popsim\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\Setup\software\popsim\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\Setup\software\popsim\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\Setup\software\popsim\lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "E:\Projects\Clients\NashvilleMPO\ModelUpdate2023\Tasks\Task4_Enhancements\Update_PopulationSim_Software\New_MultiProcessor\Setup\software\popsim\lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Projects\\Clients\\NashvilleMPO\\ModelUpdate2023\\Tasks\\Task4_Enhancements\\Update_PopulationSim_Software\\New_MultiProcessor\\Setup\\output\\DaySimFormat\\household_2017_GQ.dat'
